### ISSUE TITLE
nice project ngl

### ISSUE THREAD

**Issue by SpongeBed81** [hanzydev/SpaceX#1]

**Comment by hanzydev** [comment]
eyw kardo

**Comment by sarptekbas** [comment]
> 

![image](https://github.com/hanzydev/SpaceX/assets/47891877/ca1f8005-b557-4bc9-b661-748e7ea37293)

**Comment by SpongeBed81** [comment]
ya şimdi adam gelmiş seks yapalım diyor lan amınakoyim mert sen gey misin de gelip bana seks yapalım diyorsun amın izmirlisi. ben senin gibi değilim gidip pasif pasif kendimi siktirmiyorum mert. eğer sen siktiriyorsan onu bilemem ama ben ne geyim ne de izmirliyim. izmirli olup da gurur duyuyorsan ananın amına ayağımı sokayım.

**Comment by zukreindev** [comment]
Dalgamı geçiyorsun SpongeBed
